# Generated by Django 5.1.2 on 2025-02-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='user', max_length=255, unique=True, verbose_name='username')),
                ('email', models.EmailField(default='-', max_length=255, verbose_name='email')),
                ('fullname', models.CharField(max_length=255, verbose_name='fullname')),
                ('role', models.CharField(choices=[('coach', 'Coach'), ('athlete', 'Athlete')], default='athlete', max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
