# Generated by Django 5.1.2 on 2025-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_actors',
            field=models.ManyToManyField(blank=True, related_name='favorite_actor_of_user', to='movie.actoranddirector'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_directors',
            field=models.ManyToManyField(blank=True, related_name='favorite_director_of_user', to='movie.actoranddirector'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='favorite_genre_of_user', to='movie.genre'),
        ),
    ]
