# Generated by Django 5.1.2 on 2025-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='score',
        ),
        migrations.AddField(
            model_name='content',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
